"plugins (should come first)
source ~/.vim/plugin/plugins.vim
" shared settings and mappings with Neovim
source ~/.vim/base_config.vim

colorscheme gruvbox

" ~~~ Utility Mappings ~~~ {{{
" dotfile editing
nnoremap <silent> <leader>ev :e ~/.vim/vimrc<CR>
nnoremap <silent> <leader>es :e ~/.zshrc<CR>
nnoremap <silent> <leader>ef :execute 'edit ~/.vim/ftplugin/'
            \ .. &filetype .. '.vim'<CR>
nnoremap <silent> <leader>eu :e ~/.vim/plugin/utils.vim<CR>
nnoremap <silent> <leader>en :e ~/.vim/notes.vim<CR>
nnoremap <silent> <leader>ep :E ~/.vim/plugin/<CR>

" TRIDENT
" trident todo: (~/.vim/plugin/trident.vim)
" - remap for engram!
" - save scroll position in the window! it changes when hopping back (marks
"   and :e both do this it seems...)
" - UI (minor??)
" - [minor] 'add mark' semantics (e.g. via <leader>a) instead of only m<mark char>
set viminfo+=!
" nnoremap mj :call TridentSetMapping('j')<CR>
" nnoremap mk :call TridentSetMapping('k')<CR>
" nnoremap ml :call TridentSetMapping('l')<CR>
" nnoremap m; :call TridentSetMapping(';')<CR>
" nnoremap <C-j> :call TridentJumpToFile('j')<CR>
" nnoremap <C-k> :call TridentJumpToFile('k')<CR>
" nnoremap <C-l> :call TridentJumpToFile('l')<CR>
" Vim doesn't recognize <C-;>. I've mapped <C-;> to Option+s in iterm.
" nnoremap ß :call TridentJumpToFile(';')<CR>

command! Bdi :call DeleteInactiveBufs()
" section movement on { and } (note: vim remaps these for .vim, py, etc)
map [[ ?{<CR>w99[{
map ][ /}<CR>b99]}
map ]] j0[[%/{<CR>
map [] k$][%?}<CR>

" my lite terminal hax (~/.vim/plugin/terminal)
" philosophy: terms are lightweight and isolated/throwaway.
" - trivial to create and close
" - easy to swap back & forth (assumes you don't use tabs otherwise)
" - don't pollute buffer list
" note: an alternative to this would be 1 or 2 dedicated Ctrl-keys that open/switch
" to terminal windows, like harpoon.
nnoremap <leader>t :call CreateLiteTerm(1)<CR>ls<CR>
nnoremap <leader>T :call CreateLiteTerm(0)<CR>ls<CR>
tnoremap <F3> <C-w>gt
noremap <F3> gt
inoremap <F3> <C-o>gt

" fzf (home-row optimized, I press these the most!)
nnoremap <silent> <leader>sf :Rg<CR>
nnoremap <silent> <leader>fj :Buffers<CR>
nnoremap <silent> <leader>fk :FzfFilesUppable<CR>
nnoremap <silent> <leader>fl :Helptags<CR>
nnoremap <silent> <leader>fh :History<CR>
nnoremap <silent> <leader>fu :GFiles<CR>

" ~~ misc mappings ~~
" open last buffer in a botright split ("split previous")
nnoremap <silent> <leader>sp :execute "botright split " .. bufname("#")<CR>

" testing
" todo: fix (breaks when toggling 2x first time on grep operator plugin).
nnoremap <leader>y :call QuickfixToggle()<CR>
" nnoremap <leader>x :call FoldColumnToggle()<CR>

"==================== Operators ==================== 
" grep (plugin/grep-operator.vim) "todo: screen funkiness. redraw?
nnoremap <leader>g <Plug>GrepOperatorNormalMode
vnoremap <leader>g <Plug>GrepOperatorVisualMode

"==================== Motions ==================== 
" markdown heading in current section
onoremap ih :<c-u>execute "normal! ?^\\(=\\\|-\\)\\+$\r:nohlsearch\rkvg_"<cr>
onoremap ah :<c-u>execute "normal! ?^\\(=\\\|-\\)\\+$\r:nohlsearch\rg_vk0"<cr>

"}}}

" ~~~ Autocommands ~~~ {{{
augroup vimrc
  autocmd!
  " testing: code templates
  au FileType python iabbrev <buffer> fff def func(a: int) -> int:<cr>return 1
augroup end

augroup filetype_vim
  autocmd!
  " enable folding for Vimscript files (usage: 'za' to toggle)
  autocmd FileType vim setlocal foldmethod=marker

  " (exclude 'curdir' from viewoptions to not clobber current dir)
  let &viewoptions="folds,cursor"

  " remember folds for vimrc 
  autocmd BufWinLeave vimrc mkview
  autocmd BufWinEnter vimrc silent loadview 
augroup end
" }}}

" ~~~ Settings ~~~ {{{
" Briefly show matching brackets when text indicator is over them
" disable indents for html, though, cuz that's my Xah style
au FileType html set indentexpr=""

" }}}
