eval "$(/opt/homebrew/bin/brew shellenv)"

export LANG='en_US.UTF-8'
export LESS='-g -i -M -R -S -w -X -z-4'
export VISUAL="emacsclient -c"
export EDITOR="$VISUAL"

# openAI (i use keychain)
if command -v security >/dev/null; then
  key=$(security find-generic-password -s openai_api_key -w 2>/dev/null)
  if [[ -n "$key" ]]; then
    export OPENAI_API_KEY="$key"
  fi
fi

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Cursor Agent
export PATH="$HOME/.local/bin:$PATH"

# Go
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
