# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# disable auto correct
unsetopt correct

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# broot
source /Users/mhd/.config/broot/launcher/bash/br

# settings
export EDITOR=vim

# mine...
alias zrc="vim ~/.zshrc && source ~/.zshrc"
alias zpr="vim ~/.zprezto/runcoms"

alias ddbp="vim ~/.doordash_bash_profile.sh && source ~/.doordash_bash_profile.sh && echo 'source completed'"
source ~/.doordash_bash_profile.sh

###
# INLINE COPIED BASHRC
###

# personal projects
alias dot="cdls ~/code/dotfiles"
alias sicp="cdls ~/code/sicp"
alias alg="cdls ~/code/algorithm-study"
alias skiena="cdls ~/code/algorithm-design-manual"
alias hammer="vim ~/.hammerspoon/init.lua"
alias nand="cdls ~/code/nand2tetris"
alias site="cdls ~/code/maxdarling.github.io"

# git
alias gp="git push -u origin"
alias gpl="git pull"
alias gs="git status"
alias gc="git commit"
alias gb="git branch"
alias gl="git log"
alias gamend="git status && git commit -a --no-edit --amend"
alias gch="git checkout"
alias gmast="git checkout master && git pull origin master"
alias grc="git rebase --continue"
alias gd="git diff"
alias gemp="git commit -m \"empty commit\" --allow-empty"

# vim 
alias v="vim"
alias vp="vim ~/.vimrc"

killports() {
    for port in "$@"
    do
        kill -9 $(lsof -t -i:$port)
    done
}

# TOKENS / SECRETS
# example: git push https://maxdarling:${PERSONAL_GITHUB_TOKEN}@github.com/maxdarling/algorithm-design-manual.git
# for repos, do git remote add <above url, tweaked for repo>
source ~/.personal_github_token.sh

git_personal_remote() {
    repo="$(pwd | sed -E 's#.*/##')"
    echo "[y/n] is this the repo name?: $repo"
    read yn
    if [[ "$yn" != "y" ]]; then
        echo "exiting"
        kill -INT $$
    fi
    git remote remove origin 2>/dev/null
    str="git remote add origin https://maxdarling:${PERSONAL_GITHUB_TOKEN}@github.com/maxdarling/${repo}.git"
    eval "$str"
    echo "done"
}
