#+title Notes
#+author: MD
#+date: 3/8/2026

* TODOS
** TODO org-boring-lists cleanup
*** TODO package steps
- test package vars and options
  - i suspect that chat misunderstood my second ret-on-empty-item behavior. it matches [[https://stackedit.io/app#][online md editor]].

*** TODO cleanup below information
- S-TAB in insert mode should not call org-shifttab. rather, tab and S-tab
  should just indent normally as in a md editor or gdocs
- corfu completion accept with tab no longer works after new tab binds.
  - a more verbose fix than id like but ok for now...
- [ ] [[https://www.reddit.com/r/emacs/comments/qk15ru/cant_make_sense_of_orgmodes_indentation/][reddit]]
  
** TODO copy emacs init comments to org doc (projects, todos, etc)

** TODO learn org shortcuts
- [ ] toggle checkbox: C-c C-c (prefix arg to toggle presence)
  - it'd be nice if the dot command could repeat this! (or repeat mode?)
- org-insert-todo-heading: M-S-<RET> (need to rebind)
- C-# org-update-statistics-cookies
- more structural navigation (e.g. "{", "[[". other good ones?)

** TODO agent shell stuff
- [ ] '@' in shell completes files with /standard/ mechanism
  (*completions* buffer).

* Keybinds
** todos
***  TODO try global SPC leader (incl. <E>)
- prev blocker: term-like modes in <E>. you need SPC
- proposal: S-SPC leader.
- proposal 2: go see what spacemacs does.

this can be bound with no cost. which then enables us to implement some leader-seq style binds.

** keybinds.el (draft)
*** philosophy (top-level)
Main principles:
1. top-level binds > vim binds
   a. emacs is more than a text editor. the most important keys are the top-level ones i use in /all/ modes, e.g. switching buffer/window, GNU Readline -style keys for word/line kill/nav.
   b. note: some core vim keys (navigation) are promoted to top-level, e.g. C-u/C-d, C-e/C-y, C-w, g-.
   c. note: some top-level keys replace vim ones, e.g. s-<left/right> for fwd/back instead of C-i/C-o.
      - when this happens, C-i and C-o can become top-level keys. This is great! ("o" and "i" are prime real estate!).
2. reduce cognitive load w/ consistent interfaces
   a. the goal is a consistent interface no matter the mode. E.g. C-c C-p enables writable mode for /both/ grep and dired.
   b. spacemacs claims to be an exemplar here, and to have invested tons of hours. i should check it out. finding the patterns would be pretty cool.
   c. modern apps are good inspiration, too. E.g. s-, for "Settings" has been great.
3. lean into s- and C- when comfortable
   a. s- and C- are each adjacent to my L and R thumb's default resting positions of shift and space, repsectively.
   b. 2-key chords with 1 key per hand are very comfortable /and fast/. (this is a valid exception to anti-RSI conventional wisdom that leader sequences are king).
   c. counterexample: i'd like to give spacemacs-style leader sequences a try eventually. we'll see.
4. use <E> when necessary
   a. type 1: hyper-bespoke menu-style modes (e.g. magit). 
   b. type 2: repl modes (agent-shell, vterm). they don't play well in insert mode.
   c. note: good top-level binds help here a lot. e.g. C-i to switch window.
5. apapt modes to <N> or <M> otherwise
   a. e.g. dired in <N>: it's basically <E> but with j, k, g, /.
      - (not the best example tbh, as there's not many keys)
      - it could also be <M> since it's readonly (could switch to <N> for wdired mode)
   b. e.g. help and info in <M>: keep j, k, g, /. readonly mode, so most other keys can be free.

*** 2/11/26 keybind change journal
reflections (start of phase 1) - C-k and C-i are likely better than
"r" and "h". the latter were a bold play to make the most-common
actions 1-keystroke, which i stand by in theory. the issue is that
it doesn't work in some modes: 1. insert-always modes like terminal
(can't think of other examples) and 2. <E>-always modes like magit
(and more examples likely to follow over time). sure, you can C-x o
your way out in those cases, but that lack of uniformity actually
bugs me more I think. I hold a subconscious of those modes because
of it - they feel foreign and unwieldy to me.  And then there's
considering the next point: C-i/k is basically as comfy as h/r.  an
L/R chord is pretty decent. specifically C- because my thumb hovers
that by default when i'm in navigation-mode via C-d/u/e/y, and of
course spacebar right below it when i'm in typing mode. it's very
natural.


phase 1 (start 2/11/26, comfy 2/25/26)
- remove C-o and C-i. too vim-specific. I like s-<left/right>.
- bind C-o (strongest available key) as a prefix for core stuff (fzf file/dir, grep, etc)
- revamp "h" to be pan-modal (C-i)
- revamp "r" to be pan-modal (C-k OR C-t)
- change inc (C-[S-]a) to (C-[S-]p)
- force phase 1 changes on cursor, too :)

todo (habits):
- use C-l more for centering screen on cursor when scrolling up/down

todo:
- vterm conf (enable C-c, decide C-k, ...)
- M-<L/R> default in normal mode (and working in term) , winner to C-<L/R>
- unbind h, r (and restore help mode defaults?)
- sift though C-x to understand groupings
- read up on C-c conventions in different modes (e.g. C-c C-c is "apply changes") 
- more vs-code and browser unification
  - s-n for new empty file and s-S-n for new frame ("window")
  - ...
- cleanup xah-bound keys
  - i can keep many to look at for inspo, but i should put somewhere out of the way.
- "all modes" contains many leader sequences that are not relevant for
emacs state. i should move them to the next section "normal mode". I likely
confused the sections as one before(?).
- switch to C-s for search (this frees n for magit and other "n/p" modes)

abandoned:
- scrolling revamp
  - C-e and C-y for single line scroll, and C-u and C-d for multi line
  - why not just combine the above and use shift for the less common one?
  - it's more divergence from vim, but who cares. i'm on engram for the long haul.
  - cleanup:
    - C-a and C-S-a are inc. but too good a key for that. C-y is fine.
    - C-u/C-d free (keep C-u default)
  - reason abandoned: minor bonus to free up some keys in exchange for slightly but
  meaningfully more awkward binds for core actions. plus minor con in defying vim
  defaults. plenty of benefit in just scrapping C-a and putting universal arg on C-'

available keys:
- C (L): C-a, C-b, C-,, ...
- C (R): C-t, C-n, C-q, C-m, C-f
- S: s-LOTS

key replacement ideas:
- r and C-r.
  - why are u and C-r undo/redo? weird. i could map r to redo and then
  free up C-r for something juicy.
- C-h
  - it's core in emacs, but only as a newb now. in theory it should be less important.
  i should power-finger real estate for something more important and universal!
*** harpoon
  - i'm totally used to the visual indicators in vscode. hmm. but i could memorize e.g. for
  emacs dotfiles the seq: init, keymaps, mode keymaps, or something.
  - i should probably push myself to memorize for a couple weeks and see how it goes.
  - todo: C-c C-c as a common "apply changes" pattern on a virtual file a la. wgrep, wdired, magit.
  but i'd need to make a major mode? Why not?!
  - make it appear as a popup buffer in the center of the screen? or the minibuffer at least?
  upper left is uncomfortable for me. and modal better signifies that it's for quick changes.
    - todo: quick win: make it appear in a tiny window at bottom, mimicking the minibuffer

*** xah inspo backlog
xah has a ton of commands. some that might provide inspo. below are some i marked long ago.
# (kbd "<leader>i1") 'xah-open-in-terminal
# (kbd "<leader>ic") 'xah-copy-file-path
# (kbd "<leader>b\"") 'xah-escape-quotes
# (kbd "<leader>b\\") 'xah-space-to-newline
# (kbd "<leader>bl") 'xah-quote-lines
# (kbd "<leader>bw") 'xah-remove-whitespace
# (kbd "<leader>bd") 'xah-insert-date
# (kbd "<leader>bf") 'xah-show-formfeed-as-line
# (kbd "<leader>kz") 'xah-run-current-file
# ("TAB TAB" . indent-for-tab-command)
# ("TAB i" . complete-symbol)
# ("TAB g" . indent-rigidly)
# ("TAB r" . indent-region)
# ("TAB s" . indent-sexp)
